# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LLBlueToothDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LLBlueToothDemo

  target 'LLBlueToothDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LLBlueToothDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
